### ISSUE TITLE
geoval is not in the pypi anymore?

### ISSUE THREAD

**Issue by koldunovn** [pygeo/geoval#8] opened 2017-03-03 16:07 UTC
The link from google lead to en empty page
https://pypi.python.org/pypi/geoval/0.1.2

Search on pypi also return no results.

ping @bulli92

**Comment by bulli92** [comment] 2017-03-06 20:08
Hi Nikolay,
good to hear from you! Thanks for pointing this out. I had recently removed the last pypi version as there was some problems with the consistency with the ESMvaltool.

The problem is, that some diagnostics in the current official ESMvalTool version could not work with the most recent geoval version on pypi.

I will upload the current master again.
Guess you made it working anyway already on your machine.

Best, Alex

**Comment by koldunovn** [comment] 2017-03-06 20:36
Hello, Alex

Glad to see you still very active in development of great tools!

Without `geoval` in pypi things like [this](https://github.com/ESMValGroup/ESMValTool/blob/1d01e9d3b8409380c9ea990f24c05b5f8c0c0a53/environment.yml) will not work. 

I did manage to install `geoval` with `setup.py`, but to be honest it was not an easy ride :) The cython binaries for `polygon_utils` were somehow created in a wrong directory and I had to manually move them to the folder were they can be found. Maybe it's related to the fact that I use `conda`, but I guess this is quite common now.

Best,
Nikolay

**Comment by bulli92** [comment] 2017-03-07 08:43
Hi,


I plan to move geoval to conda now anyway.

The problem with geoval is that it is not well documented yet as we used 
it as an internal tool so far. In that sense, you are the chamion user 
which forces me to properly document and package the code.

Will do the next days. Perhaps you can then volontueer for a beta-tester 
for the installation :-)





Am 06.03.2017 um 21:36 schrieb Nikolay Koldunov:

**Comment by koldunovn** [comment] 2017-03-07 09:18
Having it on conda would simplify things a lot :) I will try to help with testing of course!

**Comment by bulli92** [comment] 2017-03-13 10:30
issue is still how to compile the dependencies when installing either using pip or conda. Could not figure out yet how this needs to be configured.

**Comment by koldunovn** [comment] 2017-03-13 11:11
My understanding is that with conda you don't compile on the user side, but distribute precompiled binaries. Maybe you can go directly for the conda-forge distribution? 
http://conda-forge.github.io/docs/

**Comment by bulli92** [comment] 2017-03-13 20:54
geoval is now available again on pypi. I am currently building a recipe to allow installation via conda-forge.
Documentation for installation was updated.

**Comment by bulli92** [comment] 2017-03-17 08:36
close this. conda packing almost done

**Closed by bulli92** 2017-03-17 08:36 UTC
